config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]  
  
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'

  get 'signup', to: 'logins#new', as: 'signup'  
  post 'login', to: 'sessions#create', as: 'login'  
  get 'logout', to: 'sessions#destroy', as: 'logout'  
   
  resources :logins
  resources :cookings
  resources :products

  #root 'cookings#index'
  #root 'products#index'
  get "/products", to: "products#index"
 
  resources :cookings, only: [:show, :edit, :update, :destroy]
  
  get 'logins', to: 'login#new' 
  #get 'logins/index'
  root 'logins#index' 

end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.httpsml

app/models/cooking.rb
class Cooking < ApplicationRecord
end

app/controllers/cookings_controller.rb
class CookingsController < ApplicationController
  
  before_action :set_cooking, only: %i[ show edit update destroy ]

  # GET /cookings or /cookings.json
  def index
    @cookings = Cooking.all
    # cookies[:current_cookings] = "ayushi"
  end

  # GET /cookings/1 or /cookings/1.json
  def show
    # The user can request to receive this resource as HTML or PDF.
    @cooking = Cooking.find(params[:id])
    
    respond_to do |format|
      format.html
      format.pdf {render pdf: generate_pdf(@cooking)}
    end
  end

  # GET /cookings/new
  def new
    @cooking = Cooking.new
  end

  # GET /cookings/1/edit
  def edit
  end

  # POST /cookings or /cookings.json
  def create
    @cooking = Cooking.new(cooking_params)

    respond_to do |format|
      if @cooking.save
        format.html { redirect_to @cooking, notice: "Cooking was successfully created." }
        format.json { render :show, status: :created, location: @cooking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookings/1 or /cookings/1.json
  def update
    respond_to do |format|
      if @cooking.update(cooking_params)
        format.html { redirect_to @cooking, notice: "Cooking was successfully updated." }
        format.json { render :show, status: :ok, location: @cooking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookings/1 or /cookings/1.json
  def destroy
    @cooking.destroy
    respond_to do |format|
      format.html { redirect_to cookings_url, notice: "Cooking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

# Generates a PDF document with information on the client and returns it. The user will get the PDF as a file download.
  def download_pdf
    client = Cooking.find(params[:id])
    send_data generate_pdf(cooking),
              filename: "#{client.title}.pdf",
              type: "application/pdf"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooking
      @cooking = Cooking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cooking_params
      params.require(:cooking).permit(:receipe, :title, :active)
    end

    def generate_pdf(cooking)
      require "prawn"
      Prawn::Document.new do
        text cooking.title, align: :center
        
        text "Recipe: #{cooking.receipe}"
      end.render
    end
end

app/helpers/cookings_helper.rb
module CookingsHelper
end

app/views/cookings/_form.html.erb
<%= form_with(model: cooking) do |form| %>
  <% if cooking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cooking.errors.count, "error") %> prohibited this cooking from being saved:</h2>

      <ul>
        <% cooking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :receipe %>
    <%= form.text_area :receipe %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cookings/edit.html.erb
<h1>Editing Cooking</h1>

<%= render 'form', cooking: @cooking %>

<%= link_to 'Show', @cooking %> |
<%= link_to 'Back', cookings_path %>

app/views/cookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cookings</h1>

<table>
  <thead>
    <tr>
      <th>Receipe</th>
      <th>Title</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cookings.each do |cooking| %>
      <tr>
        <td><%= cooking.receipe %></td>
        <td><%= cooking.title %></td>
        <td><%= cooking.active %></td>
        <td><%= link_to 'Show', cooking %></td>
        <td><%= link_to 'Edit', edit_cooking_path(cooking) %></td>
        <td><%= link_to 'Destroy', cooking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cooking', new_cooking_path %>

app/views/cookings/new.html.erb
<h1>New Cooking</h1>

<%= render 'form', cooking: @cooking %>

<%= link_to 'Back', cookings_path %>

app/views/cookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Receipe:</strong>
  <%= @cooking.receipe %>
</p>

<p>
  <strong>Title:</strong>
  <%= @cooking.title %>
</p>

<p>
  <strong>Active:</strong>
  <%= @cooking.active %>
</p>

<%= link_to 'Edit', edit_cooking_path(@cooking) %> |
<%= link_to 'Back', cookings_path %>