config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]  
  
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'

  get 'signup', to: 'logins#new', as: 'signup'  
  post 'login', to: 'sessions#create', as: 'login'  
  get 'logout', to: 'sessions#destroy', as: 'logout'  
   
  resources :logins
  resources :cookings
  resources :products

  #root 'cookings#index'
  #root 'products#index'
  get "/products", to: "products#index"
 
  resources :cookings, only: [:show, :edit, :update, :destroy]
  
  get 'logins', to: 'login#new' 
  #get 'logins/index'
  root 'logins#index' 

end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.httpsml

app/models/login.rb
class Login < ApplicationRecord
  
  #has_secure_password
  
  has_many :registrations

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX}

  validates :password, presence: true, length: {minimum: 6} 

  def authenticate(param_password)
    password == param_password
  end  
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: %i[ show edit update destroy ]

  # GET /logins or /logins.json
  def index
    @logins = Login.all
    #cookies[:current_user] = "user"
    login_user = Login.find_by_id(session[:login_id])
  end

  # GET /logins/1 or /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins or /logins.json
  def create
    @login = Login.new(login_params)

    if @login.save   
      session[:login_id] = @login.id   
      redirect_to @login, notice: 'Login successfully created.'   
    else   
      render :new   
    end   
  end 
    # if @user = Login.authenticate(params[:usrename], params[:password])
    #    cookies[:current_user_id] = @user.id
    #   redirect_to root_url
    # end
     
    # if @login.save
    #   flash[:notice] = "Thanks for your login"

    #   if params[:username]
    #     cookies[:username] = @login.username
    #   # else
    #   #   cookies.delete(:username)
    #   end
    #   render action: "show" 
    #   else
    #   render action: "new"   
    # end 
  
    # respond_to do |format|
    #   if @login.save
    #     format.html { redirect_to @login, notice: "Login was successfully created." }
    #     format.json { render :show, status: :created, location: @login }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @login.errors, status: :unprocessable_entity }
    #   end
    # end

  # PATCH/PUT /logins/1 or /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: "Login was successfully updated." }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1 or /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: "Login was successfully destroyed." }
      format.json { head :no_content }
    end
    cookies.delete(:current_user_id)
    @_current_user = nil
    flash[:notice] = "You have successfully logged out"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def login_params
      params.require(:login).permit(:username, :password)
    end
    

end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_with(model: login) do |form| %>
  <% if login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
        <% login.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<h1>Logins</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.username %></td>
        <td><%= login.password %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<p>
  <strong>Username:</strong>
  <%= @login.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.password %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>